### ISSUE TITLE
[S/|O|U]GE / DRMAA1 JobProxy

### ISSUE THREAD

**Issue by jkrue** [jkrue/jobproxy#49]
Batch grid systems like [S|O|U] Grid Engine or Torque are still popular and  often available/used on non "cloud" compute clusters to distribute job requests. Most batch grid systems supports the [DRMAA](https://www.drmaa.org/) API for a general - framework independent - way of job control. Since the latest DRMAA specification (version 2) is only supported by the Univa Grid Engine (June 2016) this plugin should use the widely spread version 1.

**Comment by pbelmann** [comment]
@jkrue  I merged your current jobproxy drmaa implementation directly to the beta dev branch:
https://github.com/jkrue/jobproxy/tree/beta.1.release

However I had to remove the Exception thrown by the constructor otherwise we would have to catch exception thrown by every framework here https://github.com/jkrue/jobproxy/blob/beta.1.release/JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java#L70-L71


We could release the fresh beta version directly with the drmaa implementation. Just the client is missing: https://github.com/jkrue/jobproxy/issues/21
